# Generated by Django 3.1.6 on 2021-02-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Date_Of_Birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
    ]
